<?php
$password = "members123@"; // Your desired plain-text password
$hashed_password = password_hash($password, PASSWORD_DEFAULT);
echo $hashed_password;





CREATE DATABASE IF NOT EXISTS helpdesk_db;
USE helpdesk_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL, -- Store hashed passwords here
    role ENUM('admin', 'ithead', 'employee', 'specialist') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sender VARCHAR(50) NOT NULL,
    receiver VARCHAR(50) NOT NULL,
    role_from ENUM('employee', 'ithead', 'specialist') NOT NULL,
    role_to ENUM('ithead', 'specialist', 'employee') NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    category ENUM('hardware', 'software', 'network', 'account', 'other') NOT NULL,
    priority ENUM('high', 'medium', 'low') NOT NULL,
    parent_id INT NULL, -- Links to the ID of the message it's a reply/forward to
    status ENUM('open', 'responded', 'forwarded', 'closed') DEFAULT 'open',
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sender) REFERENCES users(username),
    FOREIGN KEY (receiver) REFERENCES users(username),
    FOREIGN KEY (parent_id) REFERENCES messages(id)
);

-- Insert sample users (PASSWORDS ARE 'password' for all, but are hashed!)
-- IMPORTANT: Generate these hashes correctly.
-- For example, in a temporary PHP file, run: echo password_hash('password', PASSWORD_DEFAULT);
-- Then paste the output here.
-- Example hashed password for 'password' (will be different each time you generate it):
-- $2y$10$YourActualHashedPasswordHereForEmployee1
-- So, replace the placeholder hashes below with actual ones generated by password_hash().

INSERT INTO users (username, password, role) VALUES
('employee1', '$2y$10$pnZ9R0Qk2vGZfUS3hiuwmuX0I1POGQMKgFi2IJGUh2Jt581ipOysO', 'employee'), -- Replace with actual hash for 'password'
('ithead1', '$2y$10$Sp/OTAeulGUrCz4L5P9qhOYlViS9FaIJs1MomUzjzgdi6jg2FB7ai', 'ithead'),   -- Replace with actual hash for 'password'
('specialist1', '$2y$10$9eY2MJ6DBjbDS1UyedXE4uNud4lxeO7kX9r3qA8zP7/G0LzxwLL3a', 'specialist'); -- Replace with actual hash for 'password'

-- NOTE: I've put a *placeholder* hash above. You MUST generate a real hash using PHP's password_hash()
-- For example, create a file named `hash_password.php`:
-- <?php echo password_hash('password', PASSWORD_DEFAULT); ?>
-- Run this file in your browser or terminal and copy the output. Use that actual output in the INSERT statements.